version: v1alpha1 # Indicates the schema used to decode the contents.
debug: false # Enable verbose logging to the console.
persist: true
# Provides machine specific configuration options.
machine:
    type: worker # Defines the role of the machine within the cluster.
    token: aic1fh.kj4zu9kl5iz5thjb # The `token` is used by a machine to join the PKI of the cluster.
    # The root certificate authority of the PKI.
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBb0haS3p6bW9pSTFoTVUvZy9KSHJxVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qUXdOakl5TURZek9UTTBXaGNOTXpRd05qSXdNRFl6T1RNMFdqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUpweVhUMXVhdnY2SWxOVk1pY1BGYWtBSmtNQUxQOXgzN25NCmhRNkhYMHExbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRklHV0lYU2tpWFF2TVVMbgo5NThTYjZ6MVAxRTJNQVVHQXl0bGNBTkJBRDFLT0MxRmtYSGlTZDJSU0RCRkF1VE44TlcwWDF5MkxBOUhlWVFQCmF2YjdlOUIyQjk5eEY1endPbW1BbmRUeXZRZlY2VHNucEZwSjV1WVF0L2U0QlFrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: ""
    # Extra certificate subject alternative names for the machine's certificate.
    certSANs: []
    # Used to provide additional options to the kubelet.
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.30.1 # The `image` field is an optional reference to an alternative kubelet image.
        defaultRuntimeSeccompProfileEnabled: true # Enable container runtime default Seccomp profile.
        disableManifestsDirectory: true # The `disableManifestsDirectory` field configures the kubelet to get static pod manifests from the /etc/kubernetes/manifests directory.
    # Provides machine specific network configuration options.
    network: {}
    # Used to provide instructions for installations.
    install:
        disk: /dev/vda # The disk used for installations.
        image: ghcr.io/siderolabs/installer:v1.7.4 # Allows for supplying the image used to perform the installation.
        wipe: false # Indicates if the installation disk should be wiped at installation time.
    # Used to configure the machine's container image registry mirrors.
    registries: {}
    # Features describe individual Talos features that can be switched on or off.
    features:
        rbac: true # Enable role-based access control (RBAC).
        stableHostname: true # Enable stable default hostname.
        apidCheckExtKeyUsage: true # Enable checks for extended key usage of client certificates in apid.
        diskQuotaSupport: true # Enable XFS project quota support for EPHEMERAL partition and user disks.
        # KubePrism - local proxy/load balancer on defined port that will distribute
        kubePrism:
            enabled: true # Enable KubePrism support - will start local load balancing proxy.
            port: 7445 # KubePrism port.
        # Configures host DNS caching resolver.
        hostDNS:
            enabled: true # Enable host DNS caching resolver.
# Provides cluster specific configuration options.
cluster:
    id: 3Iu2l_caa0oeTkaKlhSZEjzyYKujEs-SYGPHZzeRAA0= # Globally unique identifier for this cluster (base64 encoded random 32 bytes).
    secret: PG77l7NgmJVy0rSBUGdejwxizcq3+cICl26eiExzDJo= # Shared secret of cluster (base64 encoded random 32 bytes).
    # Provides control plane specific configuration options.
    controlPlane:
        endpoint: https://10.250.0.200:6443 # Endpoint is the canonical controlplane endpoint, which can be an IP address or a DNS hostname.
    # Provides cluster specific network configuration options.
    network:
        dnsDomain: cluster.local # The domain used by Kubernetes DNS.
        # The pod subnet CIDR.
        podSubnets:
            - 10.244.0.0/16
        # The service subnet CIDR.
        serviceSubnets:
            - 10.96.0.0/12
    token: njmabq.cll4svz70n4xx9fw # The [bootstrap token](https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/) used to join the cluster.
    # The base64 encoded root certificate authority used by Kubernetes.
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUxSMzJ2Wno4OE9uTGRRM1cxUnRWQkF3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOREEyTWpJd05qTTVNelJhRncwek5EQTJNakF3TmpNNQpNelJhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVROMFF0dzhKTVR0MUNBWUpBcEM3MCtQTVZneXVrbzZZS1ZsbWUrVEk0eUFhWVpRT2hIS3BhMEx2L3EKYndYUXdBaEpiNEY3SzdIOCtCZU5yMlcvdVY1L28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGTkR0V1BVdlRBZW41cUNXQ01iaWpYQzNrK3FmTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUIyMDFxa0sKbFh3dWZNZ3JURTA5RDhlbXFKMngxOHU5MGpNMUpqaW5oS3l1QWlFQStEMVZVZXhtd2Y1dFdXM25TL0g3WnBZZgpLM2RJcWhGZ0U5YUdoVEhxQUpjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: ""
    # Configures cluster member discovery.
    discovery:
        enabled: true # Enable the cluster membership discovery feature.
        # Configure registries used for cluster member discovery.
        registries:
            # Kubernetes registry uses Kubernetes API server to discover cluster members and stores additional information
            kubernetes:
                disabled: true # Disable Kubernetes discovery registry.
            # Service registry is using an external service to push and pull information about cluster members.
            service: {}